"""Constants for the VTAC Deye Optimizer integration."""

DOMAIN = "vtac_deye_optimizer"

CONF_BATTERY_SOC = "battery_soc"
CONF_PV_POWER = "pv_power"
CONF_PV_POWER_SENSORS = "pv_power_sensors"
CONF_LOAD_POWER = "load_power"
CONF_GRID_POWER = "grid_power"
CONF_GRID_POWER_SENSORS = "grid_power_sensors"
CONF_BATTERY_CURRENT = "battery_current"
CONF_BATTERY_STATE = "battery_state"
CONF_PRICE_SENSOR = "price_sensor"

CONF_WORK_MODE = "work_mode"
CONF_GRID_CHARGING_ENABLE = "grid_charging_enable"
CONF_SOC_TARGET = "soc_target"
CONF_SOC_TARGETS = "soc_targets"
CONF_MAX_CHARGE_CURRENT = "max_charge_current"
CONF_MAX_DISCHARGE_CURRENT = "max_discharge_current"
CONF_GRID_CHARGING_CURRENT = "grid_charging_current"
CONF_GRID_MAX_EXPORT_POWER = "grid_max_export_power"
CONF_PEAK_SHAVING_ENABLE = "peak_shaving_enable"
CONF_PEAK_SHAVING_POWER = "peak_shaving_power"
CONF_PEAK_SHAVING_THRESHOLD_W = "peak_shaving_threshold_w"

CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_NOMINAL_VOLTAGE = "nominal_voltage_v"
CONF_MIN_VOLTAGE = "min_voltage_v"
CONF_MIN_SOC = "min_soc_percent"
CONF_MAX_SOC = "max_soc_percent"
CONF_TARGET_SOC = "target_soc_percent"
CONF_EXPORT_FLOOR_SOC = "export_floor_soc_percent"
CONF_MAX_CHARGE_A = "max_charge_a"
CONF_MAX_DISCHARGE_A = "max_discharge_a"
CONF_MAX_CHARGE_W = "max_charge_w"
CONF_MAX_DISCHARGE_W = "max_discharge_w"
CONF_ROUND_STEP_A = "round_step_a"
CONF_MIN_CHARGE_A = "min_charge_a"
CONF_CYCLE_COST = "cycle_cost_per_kwh"
CONF_EXPORT_ENABLED = "enable_export"
CONF_SHADOW_MODE = "shadow_mode"
CONF_AUTO_EXECUTE = "auto_execute"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_SCAN_INTERVAL = 300

MODE_CHARGE = "charge"
MODE_EXPORT = "export"
MODE_IDLE = "idle"
MODE_SELF_CONSUMPTION = "self_consumption"

DEYE_WORK_MODE_CHARGE = "Zero Export To CT"
DEYE_WORK_MODE_EXPORT = "Export First"
DEYE_WORK_MODE_SELF_USE = "Zero Export To CT"
